"use client";

interface Scores {
  cost_score: number;
  latency_score: number;
  availability_score: number;
  constraint_score: number;
  composite: number;
}

interface Alternative {
  label: string;
  change: string;
  is_primary: boolean;
  is_pareto: boolean;
  scores: Scores;
  cost: { total_monthly_usd: number };
  performance: { p95_ms: number; availability_pct: string };
  architecture: { layers: Record<string, string[]> };
}

export default function AlternativesTab({ alternatives, paretoIndices }: {
  alternatives: Alternative[];
  paretoIndices: number[];
}) {
  if (!alternatives || alternatives.length === 0) {
    return <p className="text-sm text-gray-500">No alternative candidates available.</p>;
  }

  return (
    <div className="space-y-6">
      <div>
        <p className="text-sm text-gray-600 mb-1">
          The LLM recommended one architecture. These variants were generated by swapping the
          primary compute or database service, then scored on cost, latency, availability,
          and constraints.
        </p>
        <p className="text-xs text-gray-400">
          Pareto-optimal: no other candidate is strictly better on all four dimensions simultaneously.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="border-b border-gray-200 text-left text-xs text-gray-500 uppercase tracking-wide">
              <th className="py-2 pr-4 font-medium">Variant</th>
              <th className="py-2 pr-4 font-medium text-right">$/mo</th>
              <th className="py-2 pr-4 font-medium text-right">p95 ms</th>
              <th className="py-2 pr-4 font-medium text-right">Uptime</th>
              <th className="py-2 pr-4 font-medium text-right">Score</th>
              <th className="py-2 font-medium text-center">Pareto</th>
            </tr>
          </thead>
          <tbody>
            {alternatives.map((alt, i) => (
              <tr
                key={i}
                className={`border-b border-gray-100 ${alt.is_primary ? "bg-blue-50" : ""}`}
              >
                <td className="py-3 pr-4">
                  <div className="font-medium text-gray-900">
                    {alt.label}
                    {alt.is_primary && (
                      <span className="ml-2 text-xs text-blue-600 font-normal">(LLM pick)</span>
                    )}
                  </div>
                  <div className="text-xs text-gray-500 mt-0.5">{alt.change}</div>
                </td>
                <td className="py-3 pr-4 text-right font-mono">
                  ${alt.cost?.total_monthly_usd?.toLocaleString() ?? "—"}
                </td>
                <td className="py-3 pr-4 text-right font-mono">
                  <span className={
                    (alt.performance?.p95_ms ?? 999) < 100 ? "text-green-600" :
                    (alt.performance?.p95_ms ?? 999) < 300 ? "text-yellow-600" : "text-red-600"
                  }>
                    {alt.performance?.p95_ms ?? "—"}
                  </span>
                </td>
                <td className="py-3 pr-4 text-right font-mono text-xs">
                  {alt.performance?.availability_pct ?? "—"}
                </td>
                <td className="py-3 pr-4 text-right">
                  <ScoreBar value={alt.scores?.composite ?? 0} />
                </td>
                <td className="py-3 text-center">
                  {alt.is_pareto ? (
                    <span className="inline-block rounded-full bg-green-100 text-green-700 text-xs px-2 py-0.5 font-medium">
                      Yes
                    </span>
                  ) : (
                    <span className="text-gray-300 text-xs">—</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {alternatives.map((alt, i) => (
          <div key={i} className={`rounded-lg border p-3 text-xs space-y-1 ${alt.is_pareto ? "border-green-200 bg-green-50" : "border-gray-100"}`}>
            <p className="font-medium text-gray-800 truncate">{alt.label}</p>
            <DimBar label="Cost"         value={alt.scores?.cost_score ?? 0} />
            <DimBar label="Latency"      value={alt.scores?.latency_score ?? 0} />
            <DimBar label="Availability" value={alt.scores?.availability_score ?? 0} />
            <DimBar label="Constraints"  value={alt.scores?.constraint_score ?? 0} />
          </div>
        ))}
      </div>
    </div>
  );
}

function ScoreBar({ value }: { value: number }) {
  const color = value >= 70 ? "bg-green-500" : value >= 40 ? "bg-yellow-400" : "bg-red-400";
  return (
    <div className="flex items-center gap-2">
      <div className="h-1.5 w-16 rounded bg-gray-100 overflow-hidden">
        <div className={`h-1.5 rounded ${color}`} style={{ width: `${value}%` }} />
      </div>
      <span className="text-xs text-gray-600 w-8 text-right">{value.toFixed(0)}</span>
    </div>
  );
}

function DimBar({ label, value }: { label: string; value: number }) {
  const color = value >= 70 ? "bg-green-400" : value >= 40 ? "bg-yellow-300" : "bg-red-300";
  return (
    <div className="flex items-center gap-1.5">
      <span className="text-gray-400 w-20 shrink-0">{label}</span>
      <div className="h-1 flex-1 rounded bg-gray-100 overflow-hidden">
        <div className={`h-1 rounded ${color}`} style={{ width: `${value}%` }} />
      </div>
    </div>
  );
}
